from pathlib import Path

from scagent.knowledge.parser import (
    _auto_backend_order,
    _build_mineru_cmd,
    _clean_mineru_markdown,
    _find_mineru_markdown,
    _postprocess_text,
    chunk_paper_markdown,
    sanitize_paper_text,
    split_into_sections,
)


def test_auto_backend_prefers_mineru():
    order = _auto_backend_order({"rag": {"papers": {}}})
    assert order[0] == "mineru"
    assert "pypdf" not in order


def test_build_mineru_cmd_pipeline_cpu(tmp_path):
    pdf = tmp_path / "paper.pdf"
    pdf.write_bytes(b"%PDF")
    out = tmp_path / "out"
    cfg = {"rag": {"papers": {"mineru": {"backend": "pipeline", "lang": "en"}}}}
    cmd = _build_mineru_cmd("mineru", pdf, out, cfg=cfg, legacy=False)
    assert cmd[:5] == ["mineru", "-p", str(pdf), "-o", str(out)]
    assert "-b" in cmd and "pipeline" in cmd
    assert "-l" in cmd and "en" in cmd


def test_build_mineru_cmd_legacy_magic_pdf(tmp_path):
    pdf = tmp_path / "paper.pdf"
    pdf.write_bytes(b"%PDF")
    out = tmp_path / "out"
    cfg = {"rag": {"papers": {"mineru": {"method": "auto", "lang": "en"}}}}
    cmd = _build_mineru_cmd("magic-pdf", pdf, out, cfg=cfg, legacy=True)
    assert "-m" in cmd and "auto" in cmd
    assert "--lang" in cmd


def test_find_mineru_markdown_prefers_stem(tmp_path):
    nested = tmp_path / "paper" / "auto"
    nested.mkdir(parents=True)
    (nested / "paper.md").write_text("# Title\n\nBody", encoding="utf-8")
    (nested / "notes.md").write_text("x", encoding="utf-8")
    found = _find_mineru_markdown(tmp_path, "paper")
    assert found.name == "paper.md"


def test_clean_mineru_markdown_strips_details_and_images():
    raw = "# T\n\n![](images/x.jpg)\n\n<details><summary>fig</summary>noise</details>\n\nReal text."
    cleaned = _clean_mineru_markdown(raw)
    assert "details" not in cleaned
    assert "images/" not in cleaned
    assert "Real text" in cleaned


def test_postprocess_strips_journal_noise():
    raw = "Nature Methods\nReceived: 1 Jan 2020\nhttps://doi.org/10.1234\nReal title line here\n\nAbstract\nBody text."
    cleaned = _postprocess_text(raw)
    assert "Nature Methods" not in cleaned
    assert "doi.org" not in cleaned
    assert "Real title line here" in cleaned
    assert "Body text" in cleaned


def test_sanitize_paper_text_removes_garble():
    from scagent.knowledge.parser import sanitize_paper_text

    raw = (
        "Current best practices in single<sub>-</sub>cell RNA<sub>-</sub>seq\n"
        "using the data generated by the 10\x03 Genomics Chromium system\n"
        "detection limit p\x05 corresponds to &nbsp; threshold\n"
        "soft\u00adhyphen and\u200bzero"
    )
    cleaned = sanitize_paper_text(raw)
    assert "<sub>" not in cleaned
    assert "single-cell" in cleaned
    assert "\x03" not in cleaned and "\x05" not in cleaned
    assert "10x Genomics" in cleaned
    assert "&nbsp;" not in cleaned
    assert "\u00ad" not in cleaned and "\u200b" not in cleaned
    assert "�" not in cleaned


def test_normalize_numbered_headings():
    from scagent.knowledge.parser import _normalize_section

    assert _normalize_section("1. INTRODUCTION") == "introduction"
    assert _normalize_section("2. DATA DESCRIPTION") == "methods"
    assert _normalize_section("SUMMARY") == "abstract"


def test_split_sections_drops_references():
    raw = """
Single-cell RNA sequencing best practices

Abstract
We review QC and integration.

Introduction
Background on droplet methods.

Methods
We used Scanpy and Harmony on PCA embeddings.

Results
Harmony outperformed naive merge on batch mixing metrics.

References
1. Author et al. Nature 2020.
2. Another paper DOI 10.1234/example
"""
    sections = split_into_sections(raw)
    assert "abstract" in sections
    assert "methods" in sections
    assert "results" in sections
    assert "references" not in sections
    assert "Harmony" in sections["methods"]


def test_chunk_paper_markdown_tags_sections():
    md = """# Harmony integration paper

## Abstract

Batch correction is essential.

## Methods

Run Harmony on PCA with batch key sample.

## Results

iLISI improved after correction.
"""
    chunks = chunk_paper_markdown(md, source="knowledge/papers/.parsed/test.md", stem="test", chunk_size=400, overlap=50)
    assert chunks
    sections = {c["section"] for c in chunks}
    assert "methods" in sections
    assert any("Harmony" in c["text"] for c in chunks)


def test_search_paper_knowledge_boosts_methods(monkeypatch):
    from rag.retriever import search_paper_knowledge

    fake = [
        {"source": "a.md", "stem": "a", "section": "abstract", "text": "Harmony batch", "score": 1.0},
        {"source": "b.md", "stem": "b", "section": "methods", "text": "Harmony on PCA", "score": 0.9},
    ]

    def _fake_retrieve(*_a, **_k):
        return fake

    monkeypatch.setattr("rag.retriever.retrieve", _fake_retrieve)
    hits = search_paper_knowledge("Harmony vs Seurat integration", top_k=2)
    assert hits[0]["section"] == "methods"
