"""Interactive scagent init wizard."""

from __future__ import annotations

import yaml

from scagent.cli import build_parser, cmd_init
from scagent.config import load_config
from scagent.init_wizard import (
    build_run_argv,
    collect_session,
    default_query,
    format_command,
    resource_overlay,
    write_overlay,
    write_session,
)


def test_cli_init_parser():
    p = build_parser()
    args = p.parse_args(["init", "--yes", "--data", "x.h5ad", "--task", "qc", "--n-jobs", "4"])
    assert args.func is cmd_init
    assert args.yes is True
    assert args.task == "qc"
    assert args.n_jobs == 4


def test_collect_defaults_and_run_argv():
    cfg = load_config()
    session = collect_session(
        answers={"data": "tests/data/tiny_100cells.h5ad", "tissue": "pbmc", "task": "annotate"},
        use_defaults=True,
        cfg=cfg,
        output_fn=lambda _s: None,
    )
    assert session["tissue"] == "pbmc"
    assert session["qc_only"] is False
    assert session["execute"] is False
    assert "质控" in session["query"] or "注释" in session["query"]
    argv = build_run_argv(session)
    assert argv[0] == "run"
    assert "--dry-run" in argv
    assert "--tissue" in argv
    cmd = format_command(session)
    assert "scagent run" in cmd
    assert "tiny_100cells.h5ad" in cmd


def test_task_number_and_qc_only():
    session = collect_session(
        answers={"data": "", "tissue": "tumor", "task": "2"},
        use_defaults=True,
        output_fn=lambda _s: None,
    )
    assert session["task"] == "qc"
    assert session["qc_only"] is True
    assert "--qc-only" in build_run_argv(session)


def test_interactive_prompts_use_input_fn():
    replies = iter(
        [
            "data.h5ad",
            "brain",
            "4",
            "",
            "n",
            "python",
            "zh",
            "8192",
            "2",
            "120",
            "batch",
            "n",
        ]
    )
    session = collect_session(
        use_defaults=False,
        input_fn=lambda _p: next(replies),
        output_fn=lambda _s: None,
        cfg=load_config(),
    )
    assert session["tissue"] == "brain"
    assert session["task"] == "trajectory"
    assert session["memory_mb"] == 8192
    assert session["n_jobs"] == 2
    assert session["timeout_seconds"] == 120
    assert session["batch_key"] == "batch"
    overlay = resource_overlay(session, load_config())
    assert overlay.get("sandbox", {}).get("memory_mb") == 8192
    assert overlay.get("performance", {}).get("n_jobs") == 2
    assert overlay.get("analysis", {}).get("timeout_seconds") == 120


def test_write_session_and_overlay(tmp_path):
    session = {
        "data": "x.h5ad",
        "tissue": "pbmc",
        "task": "annotate",
        "query": default_query("annotate", "pbmc"),
        "execute": False,
        "qc_only": False,
        "language": "python",
        "report_lang": "zh",
        "memory_mb": 4096,
        "n_jobs": 2,
        "timeout_seconds": 90,
        "batch_key": "",
        "condition_key": "",
        "interrupt": False,
    }
    sp = write_session(session, tmp_path / "init.yaml")
    loaded = yaml.safe_load(sp.read_text(encoding="utf-8"))
    assert loaded["tissue"] == "pbmc"
    overlay = resource_overlay(session, load_config())
    op = write_overlay(overlay, tmp_path / "config.local.yaml")
    text = op.read_text(encoding="utf-8")
    assert text.startswith("# Generated by scagent init")
    assert "n_jobs: 2" in text
    assert "api_key" not in text.lower()


def test_cmd_init_yes_writes_session(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("scagent.init_wizard.session_path", lambda cfg=None: tmp_path / "init.yaml")
    monkeypatch.setattr("scagent.init_wizard.overlay_path", lambda cfg=None: tmp_path / "config.local.yaml")
    args = build_parser().parse_args(
        [
            "init",
            "--yes",
            "--data",
            str(tmp_path / "cells.h5ad"),
            "--tissue",
            "pbmc",
            "--task",
            "annotate",
            "--n-jobs",
            "2",
        ]
    )
    assert cmd_init(args) == 0
    out = capsys.readouterr().out
    assert "scagent run" in out
    assert (tmp_path / "init.yaml").is_file()
    local = (tmp_path / "config.local.yaml").read_text(encoding="utf-8")
    assert "n_jobs: 2" in local


def test_load_config_merges_local_overlay(tmp_path):
    main = tmp_path / "config.yaml"
    main.write_text("sandbox:\n  memory_mb: 100\nperformance:\n  n_jobs: -1\n", encoding="utf-8")
    (tmp_path / "config.local.yaml").write_text("performance:\n  n_jobs: 3\n", encoding="utf-8")
    try:
        cfg = load_config(main, reload=True)
        assert cfg["sandbox"]["memory_mb"] == 100
        assert cfg["performance"]["n_jobs"] == 3
        assert cfg.get("_local_config")
    finally:
        load_config(reload=True)
