"""Interactive `scagent init` wizard. No API keys in YAML."""

from __future__ import annotations

import shlex
from pathlib import Path
from typing import Any, Callable

import yaml

from scagent.config import REPO_ROOT, _deep_merge, cfg_get, load_config, resolve_path

TASKS: tuple[tuple[str, str], ...] = (
    ("annotate", "标准质控 + 聚类 + 注释"),
    ("qc", "只要质控"),
    ("deg", "条件比较 / 差异表达"),
    ("trajectory", "轨迹 / 细胞命运"),
    ("custom", "自定义（自己写一句话）"),
)

LOCAL_HEADER = "# Generated by scagent init. Do not put API keys here.\n"


def default_query(task: str, tissue: str) -> str:
    t = tissue or "该组织"
    return {
        "annotate": f"对 {t} 做标准质控、聚类和注释",
        "qc": f"对 {t} 做质控",
        "deg": f"比较 {t} 对照组与处理组的差异表达",
        "trajectory": f"评估 {t} 是否含连续分化轨迹，并拟合分化轴与基因趋势",
        "custom": f"对 {t} 做标准分析",
    }.get(task, f"对 {t} 做标准分析")


def tissue_choices(cfg: dict | None = None) -> list[str]:
    keys = [str(k) for k in ((cfg or {}).get("qc_profiles") or {})]
    return keys or ["pbmc", "tumor", "brain", "heart", "liver", "kidney", "embryo", "default"]


def _as_bool(raw: Any, default: bool = False) -> bool:
    if raw is None or raw == "":
        return default
    if isinstance(raw, bool):
        return raw
    return str(raw).strip().lower() in {"1", "y", "yes", "true", "是", "执行"}


def _as_int(raw: Any, default: int) -> int:
    if raw is None or raw == "":
        return default
    return int(raw)


def _ask(
    prompt: str,
    default: Any,
    *,
    key: str,
    answers: dict | None,
    use_defaults: bool,
    input_fn: Callable[[str], str],
) -> str:
    shown = "" if default is None else str(default)
    if answers and answers.get(key) not in (None, ""):
        return str(answers[key])
    if use_defaults:
        return shown
    suffix = f" [{shown}]" if shown != "" else ""
    raw = input_fn(f"{prompt}{suffix}: ")
    return shown if not str(raw).strip() else str(raw).strip()


def collect_session(
    *,
    answers: dict[str, Any] | None = None,
    use_defaults: bool = False,
    input_fn: Callable[[str], str] | None = None,
    output_fn: Callable[[str], None] | None = None,
    cfg: dict | None = None,
) -> dict[str, Any]:
    """Ask (or fill from answers/--yes) and return a run session dict."""
    cfg = cfg or load_config()
    answers = {k: v for k, v in (answers or {}).items() if v not in (None, "")}
    ask = input_fn or input
    out = output_fn or print
    tissues = tissue_choices(cfg)
    mem_default = int(cfg_get(cfg, "sandbox.memory_mb", 16384) or 16384)
    jobs_default = int(cfg_get(cfg, "performance.n_jobs", -1) if cfg_get(cfg, "performance.n_jobs", -1) is not None else -1)
    timeout_default = int(cfg_get(cfg, "analysis.timeout_seconds", 600) or 600)

    out("scAgent 配置向导。密钥只用环境变量 OPENAI_API_KEY，不要写进 YAML。")
    data = _ask("数据路径（h5ad / loom / Cell Ranger outs / 10x / Seurat .rds；逗号分隔多样本）", "", key="data", answers=answers, use_defaults=use_defaults, input_fn=ask)
    if data and not Path(data).expanduser().exists():
        out(f"注意：路径还不存在：{data}（仍可先规划）")
    out("组织类型: " + ", ".join(tissues))
    tissue = _ask("组织", "pbmc", key="tissue", answers=answers, use_defaults=use_defaults, input_fn=ask).lower()
    if tissue not in tissues:
        out(f"未在 qc_profiles 中找到 {tissue}，将用 default 阈值并保留该名字。")
    out("分析任务:")
    for i, (_tid, label) in enumerate(TASKS, 1):
        out(f"  {i}) {label}")
    task_raw = _ask("任务编号或 id", "annotate", key="task", answers=answers, use_defaults=use_defaults, input_fn=ask)
    task_ids = [t[0] for t in TASKS]
    if task_raw.isdigit() and 1 <= int(task_raw) <= len(TASKS):
        task = TASKS[int(task_raw) - 1][0]
    elif task_raw.lower() in task_ids:
        task = task_raw.lower()
    else:
        task = "annotate"
    query = _ask("任务描述", default_query(task, tissue), key="query", answers=answers, use_defaults=use_defaults, input_fn=ask)
    execute = _as_bool(
        _ask("真正执行脚本？y=执行 / n=只生成脚本", "n", key="execute", answers=answers, use_defaults=use_defaults, input_fn=ask),
        False,
    )
    language = _ask("分析语言 python / r", "python", key="language", answers=answers, use_defaults=use_defaults, input_fn=ask).lower()
    if language not in {"python", "r"}:
        language = "python"
    report_lang = _ask("报告语言 zh / en / both", "zh", key="report_lang", answers=answers, use_defaults=use_defaults, input_fn=ask).lower()
    if report_lang not in {"zh", "en", "both"}:
        report_lang = "zh"
    memory_mb = _as_int(_ask("内存上限 MB（sandbox，仅 subprocess jail）", mem_default, key="memory_mb", answers=answers, use_defaults=use_defaults, input_fn=ask), mem_default)
    n_jobs = _as_int(_ask("CPU 并行 n_jobs（-1=全部）", jobs_default, key="n_jobs", answers=answers, use_defaults=use_defaults, input_fn=ask), jobs_default)
    timeout = _as_int(_ask("单阶段超时秒", timeout_default, key="timeout", answers=answers, use_defaults=use_defaults, input_fn=ask), timeout_default)
    batch_key = _ask("批次列名（无多样本可空）", "", key="batch_key", answers=answers, use_defaults=use_defaults, input_fn=ask)
    condition_key = ""
    if task == "deg" or "差异" in query:
        condition_key = _ask("条件列名（condition / group / treatment）", "", key="condition_key", answers=answers, use_defaults=use_defaults, input_fn=ask)
    else:
        condition_key = str(answers.get("condition_key") or "")
    interrupt = _as_bool(
        _ask("线粒体/resolution 人工确认（HITL）？", "n", key="interrupt", answers=answers, use_defaults=use_defaults, input_fn=ask),
        False,
    )
    session = {
        "data": str(Path(data).expanduser()) if data else "",
        "tissue": tissue or "default",
        "task": task,
        "query": query,
        "execute": execute,
        "qc_only": task == "qc",
        "language": language,
        "report_lang": report_lang,
        "memory_mb": memory_mb,
        "n_jobs": n_jobs,
        "timeout_seconds": timeout,
        "batch_key": batch_key,
        "condition_key": condition_key,
        "interrupt": interrupt,
    }
    return session


def resource_overlay(session: dict[str, Any], cfg: dict | None = None) -> dict[str, Any]:
    cfg = cfg or load_config()
    overlay: dict[str, Any] = {}
    if int(session["memory_mb"]) != int(cfg_get(cfg, "sandbox.memory_mb", 16384) or 16384):
        overlay.setdefault("sandbox", {})["memory_mb"] = int(session["memory_mb"])
    jobs_now = cfg_get(cfg, "performance.n_jobs", -1)
    jobs_now = -1 if jobs_now is None else int(jobs_now)
    if int(session["n_jobs"]) != jobs_now:
        overlay.setdefault("performance", {})["n_jobs"] = int(session["n_jobs"])
    if int(session["timeout_seconds"]) != int(cfg_get(cfg, "analysis.timeout_seconds", 600) or 600):
        overlay.setdefault("analysis", {})["timeout_seconds"] = int(session["timeout_seconds"])
    return overlay


def build_run_argv(session: dict[str, Any]) -> list[str]:
    argv = ["run", session["query"], "--tissue", session["tissue"], "--language", session["language"], "--report-lang", session["report_lang"]]
    if session.get("data"):
        argv.extend(["--data", session["data"]])
    argv.append("--execute" if session.get("execute") else "--dry-run")
    if session.get("qc_only"):
        argv.append("--qc-only")
    if session.get("interrupt"):
        argv.append("--interrupt")
    if session.get("batch_key"):
        argv.extend(["--batch-key", session["batch_key"]])
    if session.get("condition_key"):
        argv.extend(["--condition-key", session["condition_key"]])
    return argv


def format_command(session: dict[str, Any]) -> str:
    return "scagent " + " ".join(shlex.quote(x) for x in build_run_argv(session))


def write_session(session: dict[str, Any], path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(session, allow_unicode=True, sort_keys=False), encoding="utf-8")
    return path


def write_overlay(overlay: dict[str, Any], path: Path) -> Path | None:
    if not overlay:
        return None
    prev: dict[str, Any] = {}
    if path.is_file():
        prev = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if not isinstance(prev, dict):
            prev = {}
    merged = _deep_merge(prev, overlay)
    path.write_text(LOCAL_HEADER + yaml.safe_dump(merged, allow_unicode=True, sort_keys=False), encoding="utf-8")
    return path


def summarize(session: dict[str, Any]) -> str:
    lines = [
        f"数据: {session.get('data') or '（未填，仅规划）'}",
        f"组织: {session.get('tissue')}  任务: {session.get('task')}",
        f"描述: {session.get('query')}",
        f"执行: {'是 --execute' if session.get('execute') else '否 --dry-run'}",
        f"语言: {session.get('language')}  报告: {session.get('report_lang')}",
        f"资源: memory_mb={session.get('memory_mb')} n_jobs={session.get('n_jobs')} timeout={session.get('timeout_seconds')}s",
    ]
    if session.get("batch_key"):
        lines.append(f"批次列: {session['batch_key']}")
    if session.get("condition_key"):
        lines.append(f"条件列: {session['condition_key']}")
    if session.get("interrupt"):
        lines.append("HITL: 开")
    lines.append("命令: " + format_command(session))
    return "\n".join(lines)


def session_path(cfg: dict | None = None) -> Path:
    cfg = cfg or load_config()
    return resolve_path(cfg, "outputs") / "init.yaml"


def overlay_path(cfg: dict | None = None) -> Path:
    cfg = cfg or load_config()
    raw = cfg.get("_config_path")
    if raw:
        return Path(raw).with_name("config.local.yaml")
    return REPO_ROOT / "config.local.yaml"
