"""Scanpy script template used when no LLM is configured, and as a scaffold for bio_coder."""

from __future__ import annotations

from textwrap import dedent


def scanpy_script(meta: dict, qc: dict) -> str:
    path = meta.get("data_path") or "INPUT.h5ad"
    species = meta.get("species") or "human"
    mt_prefix = "MT-" if species != "mouse" else "mt-"
    sample_key = repr(meta.get("sample_key") or "sample")
    path_r = repr(path)
    mt_r = repr(mt_prefix)
    nmads = int(qc.get("nmads") or 5)
    tissue = meta.get("tissue") or "default"

    if str(path).endswith("/") or "filtered_feature_bc_matrix" in str(path):
        load_block = (
            f"adata = sc.read_10x_mtx({path_r}, var_names='gene_symbols', cache=True)\n"
            "adata.var_names_make_unique()"
        )
    else:
        load_block = f"adata = sc.read_h5ad({path_r})"

    if meta.get("need_batch_correction"):
        harmony_block = dedent(
            f"""\
            # Batch correction (Harmony on PCA). Do not treat UMAP mixing as success.
            sc.external.pp.harmony_integrate(adata, key={sample_key})
            sc.pp.neighbors(adata, use_rep="X_pca_harmony")"""
        )
    else:
        harmony_block = "sc.pp.neighbors(adata, n_neighbors=15, n_pcs=40)"

    script = dedent(
        f"""\
        # Auto-generated by scAgent bio_coder. Tissue={tissue}, species={species}.
        import numpy as np
        import scanpy as sc
        from pathlib import Path
        from scipy.stats import median_abs_deviation

        sc.settings.verbosity = 3
        sc.settings.set_figure_params(dpi=120, facecolor="white")
        fig_dir = Path("figures")
        fig_dir.mkdir(exist_ok=True)
        sc.settings.figdir = str(fig_dir)

        __LOAD_BLOCK__
        adata.var_names_make_unique()
        if {sample_key} not in adata.obs.columns:
            adata.obs[{sample_key}] = "sample1"

        adata.var["mt"] = adata.var_names.str.startswith({mt_r})
        adata.var["ribo"] = adata.var_names.str.upper().str.startswith(("RPS", "RPL"))
        adata.var["hb"] = adata.var_names.str.contains(r"^HB[^(P)]", case=False, regex=True)
        sc.pp.calculate_qc_metrics(
            adata, qc_vars=["mt", "ribo", "hb"], percent_top=None, log1p=False, inplace=True
        )

        sc.pl.violin(
            adata,
            ["n_genes_by_counts", "total_counts", "pct_counts_mt"],
            jitter=0.4,
            multi_panel=True,
            save="_qc_violin.png",
            show=False,
        )
        sc.pl.scatter(adata, x="total_counts", y="n_genes_by_counts", save="_qc_scatter_counts.png", show=False)
        sc.pl.scatter(adata, x="total_counts", y="pct_counts_mt", save="_qc_scatter_mt.png", show=False)

        def mad_outlier(metric: str, nmads: int = {nmads}):
            x = adata.obs[metric]
            med = np.median(x)
            mad = median_abs_deviation(x)
            return (x < med - nmads * mad) | (x > med + nmads * mad)

        adata.obs["outlier"] = (
            mad_outlier("log1p_total_counts")
            | mad_outlier("log1p_n_genes_by_counts")
            | mad_outlier("pct_counts_mt")
        )
        n_out = int(adata.obs["outlier"].sum())
        print(f"MAD outliers to remove: {{n_out}}")
        adata = adata[~adata.obs["outlier"]].copy()
        sc.pp.filter_genes(adata, min_cells=3)

        adata.layers["counts"] = adata.X.copy()
        sc.pp.normalize_total(adata, target_sum=1e4)
        sc.pp.log1p(adata)
        sc.pp.highly_variable_genes(adata, n_top_genes=2000, subset=False)
        adata.raw = adata
        sc.pp.scale(adata, max_value=10)
        sc.tl.pca(adata, svd_solver="arpack")
        __HARMONY_BLOCK__
        sc.tl.umap(adata)
        sc.tl.leiden(adata, resolution=0.6, key_added="leiden")
        sc.pl.umap(adata, color=["leiden", {sample_key}, "pct_counts_mt"], save="_overview.png", show=False)

        sc.tl.rank_genes_groups(adata, "leiden", method="wilcoxon")
        sc.pl.rank_genes_groups(adata, n_genes=15, save="_markers.png", show=False)
        print("Exploratory Wilcoxon only; group-level DE must use pseudobulk + FDR.")

        adata.write("adata_processed.h5ad")
        print(adata)
        """
    )
    return script.replace("__LOAD_BLOCK__", load_block).replace("__HARMONY_BLOCK__", harmony_block)
